Replace module with conda environment

diff --git a/esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/site/metoffice-env b/esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/site/metoffice-env
--- a/esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/site/metoffice-env
+++ b/esmvaltool/utils/recipe_test_workflow/recipe_test_workflow/site/metoffice-env
@@ -12,20 +12,20 @@
 #   COMMAND             The command to execute with options
 set -eu
 
-module_count(){
-    module list -t 2>&1 | wc -l
-}
+# module_count(){
+#     module list -t 2>&1 | wc -l
+# }
 
-safe_load(){
-    PRE_LOAD_COUNT=$(module_count)
+# safe_load(){
+#     PRE_LOAD_COUNT=$(module_count)
 
-    module load "${1}"
-    # Check module count to determine whether module load was successful.
-    if (( PRE_LOAD_COUNT == $(module_count) )); then
-        echo "[ERROR] Failed to load: ${1}"
-        exit 1
-    fi
-}
+#     module load "${1}"
+#     # Check module count to determine whether module load was successful.
+#     if (( PRE_LOAD_COUNT == $(module_count) )); then
+#         echo "[ERROR] Failed to load: ${1}"
+#         exit 1
+#     fi
+# }
 
 # Must be run before importing numpy, see
 # https://www-avd/sci/dask_best_practice/numpy-threads.html.
@@ -38,7 +38,9 @@ export NUMEXPR_NUM_THREADS=1
 # Ensure '~/.local' isn't added to 'sys.path'.
 export PYTHONNOUSERSITE=True
 
-safe_load "${MODULE_NAME}"
+# safe_load "${MODULE_NAME}"
+eval "$(conda shell.bash hook)"
+conda activate rtw-env
 
 # If PYTHONPATH_PREPEND has been set, prepend it to PYTHONPATH to extend the
 # Python environment.
